site_name: JanusGraph 翻译版(0.3.1)
site_author: FinSightRD


nav:
- 首页: index.md
- I.介绍: 
  - 1.JanusGraph优势: ./introduction/the_benefits_of_janusgraph.md
  - 2.架构总览: ./introduction/architectural_overview.md
  - 3.开始: ./introduction/getting_started.md

- II.Janusgraph基础知识:
  - 4.基本配置: ./janusgraph_basics/configuration.md
  - 5.数据实例和数据模型: ./janusgraph_basics/schema_and_data_modeling.md
  - 6.Gremin查询语言: ./janusgraph_basics/gremlin_query_language.md
  - 7.JanusGraph服务: ./janusgraph_basics/janusgraph_server.md
  - 8.部署方案: ./janusgraph_basics/deployment_scenarios.md
  - 9.配置图工厂: ./janusgraph_basics/configuredgraphfactory.md
  - 10.多节点JanusGraph集群中需要考虑的事项: ./janusgraph_basics/things_to_consider_in_a_multi_node_janusgraph_cluster.md
  - 11.高性能索引: ./janusgraph_basics/indexing_for_better_performance.md
  - 12.事务: ./janusgraph_basics/transactions.md
  - 13.JanusGraph缓存: ./janusgraph_basics/janusgraph_cache.md
  - 14.JanusGraph日志: ./janusgraph_basics/transaction_log.md
  - 15.配置手册: ./janusgraph_basics/configuration_reference.md
  - 16.常见问题: ./janusgraph_basics/common_questions.md
  - 17.技术限制: ./janusgraph_basics/technical_limitations.md

- III.存储后端: 
  - 18.Apache Cassandra: ./storage_backend/apache_cassandra.md
  - 19.Apache Hbase: ./storage_backend/apache_hbase.md

- IV. 后端索引:
  - 23.查询语法和数据类型: ./index_backends/search_predicates_and_data_types.md
  - 24.索引参数和全文搜索: ./index_backends/index_parameters_and_full-text_search.md
  - 25.字段映射: ./index_backends/field_mapping.md
  - 26.直接索引查询: ./index_backends/direct_index_query.md
  - 27.Elasticsearch: ./index_backends/elasticsearch.md
  - 28.Apache Solr: ./index_backends/apache_solr.md
  - 29.Apache_Lucene: ./index_backends/apache_lucene.md

- V. 高级特性:
  - 30.Advanced Schema: ./advanced_topics/advanced_schema.md
  - 31.最终一致的存储后端: ./advanced_topics/eventually_consistent_storage_backends.md
  - 32.失败 & 重试: ./advanced_topics/failure_recovery.md
  - 33.索引管理: ./advanced_topics/index_management.md
  - 34.批量加载: ./advanced_topics/bulk_loading.md
  - 35.图分区: ./advanced_topics/graph_partitioning.md
  - 36.数据类型和属性序列化配置: ./advanced_topics/datatype_and_attribute_serializer_configuration.md
  - 37.JanusGraph基于TinkerPop's Hadoop-Gremlin使用: ./advanced_topics/janusgraph_with_tinkerPops_hadoop_gremlin.md
  - 38.JanusGraph监控: ./advanced_topics/advanced_schema.md
  - 39.从Titan迁移: ./advanced_topics/migrating_from_titan.md

theme: readthedocs
